admin:
  password: password

datasources:
  secretDefinition:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
#        url: http://prometheus.monitoring.svc.cluster.local
        url: prometheus-server.monitoring.svc.cluster.local
        version: 1
        editable: true
        isDefault: true
      - name: Alertmanager
        uid: alertmanager
        type: alertmanager
        access: proxy
        orgId: 1
#        url: http://prometheus-alertmanager.monitoring.svc.cluster.local:9093
        url: prometheus-alertmanager.monitoring.svc.cluster.local
        version: 1
        editable: true